[general]
import = ["~/.config/alacritty/themes/carbonfox.toml"]

[window]
padding = { x = 7, y = 7 }
decorations = "none"

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
